### PR TITLE
Fix socket timeout

### PR DESCRIPTION
**Pull request by fernandodev**
In this PR I did some improvements for error handling. 
1. After sometime iOS system closes any background job it occurs faster when device locks. So after unlocking socket was disposed and the connection was lost. Trying an access with plugins or webview content will cause a runtime crash.
2. I removed some assert and in some points I changed by a runtime exception with a better error description.
3. A small usage sample was added
4. I added more details in README

### CODE REVIEW

**Comment by fernandodev** [comment]
## TODO
- [x] remove runtime exceptions
- [ ] restart server if it is unreachable 
- [ ] merge sample with sample repository
- [ ] splice sample in another `xcodeproj`

Something more?

**Comment by xwv** [comment]
There are too many commits for various topic in this PR, make it hard to review. Could you please squash related commits for 1 topic, and 1 PR for 1 topic? Thanks.

**Comment by fernandodev** [comment]
Sorry for that :disappointed: . I strangled this PR making to many commits out of context.

**Comment by xwv** [comment]
Close because #17 is fixed.

BTW, please do NOT create branches in this repo for pull request. You should fork the repo for preparing PR and create pull request in your repo when it ready. Branches in this repo are only for release or development collaboration instead of personal workspace.

**Pull request closed without merging**
