### PR TITLE
Swift 4 Migration

### PR DESCRIPTION
**Pull request by jkerrwilson**
This is a starting point for swift 4 migration for iOS 11. As far as I can tell in my application the library is working normally; however, I do not use all features, and have limited time to put further work into the migration.

This version should probably be put on a separate branch for further work. Not all tests are passing at this juncture, and I do not have the expertise to fix it.

### CODE REVIEW

**Comment by randomiser** [comment]
Is there any chance we can get this considered for merging? 

I've got a couple of projects that use XWebView that are both currently broken due to XCode9 and module issues.

Thanks heaps!

**Review by sunweifeng — APPROVED** [review]

**Comment by jkerrwilson** [comment]
I've added a commit which "fixes" two of the warnings in MetaObejct I mention in #85. Some wonky stuff with unsafe pointers in swift 4 that do not seem very well documented by Apple. I think the pushed changes provide a satisfactory workaround to the failures, but maybe someone else actually knows what they are doing.

**Comment by xwv** [comment]
Thanks for the PR. The migration is not just make the compiler happy. Passing all unit tests is important. Meanwhile, adoption of new language features is also better to have.
I'll try to migrate to swift 3.2 firstly and make sure all unit tests can be passed. Then, try to migrate to 4.0.

**Comment by randomiser** [comment]
Thanks Guys! Totally appreciate the extra effort to get this sorted.

**Comment by xwv** [comment]
My first PR #91 for Swift 3.2 porting. It passed all unit tests both on iOS and MacOS on my local machine. I'll merge it soon after pass travis ci.

**Comment by xwv** [comment]
PR #92 for Swift 4.0 migration

**Pull request closed without merging**
